apiVersion: batch/v1
kind: CronJob
metadata:
  name: collector-cron
spec:
  schedule: "*/1 * * * *"  # toutes les minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: collector
            image: docker.io/gautierjourdon/collector:latest
            # Si tu veux passer un flag pour d√©sactiver facilement
            env:
            - name: ENABLE_COLLECTOR
              value: "true"
          restartPolicy: OnFailure
